# Numpy3

## 1)Assignment
## np.min
## np.mean
## np.sum

In [1]:
import numpy as np

In [2]:
a = np.random.randn(3,4)
a

array([[ 1.8841606 , -1.15748318, -1.27033736, -1.32785245],
       [ 0.04681295, -0.53534059, -0.31887713, -0.42928778],
       [-0.59403076, -0.22432599,  1.14596339,  1.00624313]])

In [3]:
np.min(a,axis=1)

array([-1.32785245, -0.53534059, -0.59403076])

In [4]:
np.mean(a,axis=1)

array([-0.4678781 , -0.30917314,  0.33346244])

In [5]:
np.sum(a,axis=1)

array([-1.87151239, -1.23669255,  1.33384978])

## 2) Add -2 in each row of a

In [6]:
a

array([[ 1.8841606 , -1.15748318, -1.27033736, -1.32785245],
       [ 0.04681295, -0.53534059, -0.31887713, -0.42928778],
       [-0.59403076, -0.22432599,  1.14596339,  1.00624313]])

In [7]:
# Method 1
np.append(a,[[-2],[-2],[-2]],axis=1)

array([[ 1.8841606 , -1.15748318, -1.27033736, -1.32785245, -2.        ],
       [ 0.04681295, -0.53534059, -0.31887713, -0.42928778, -2.        ],
       [-0.59403076, -0.22432599,  1.14596339,  1.00624313, -2.        ]])

In [8]:
# Method 2
np.append(a,np.array([[-2],[-2],[-2]]),axis=1)

array([[ 1.8841606 , -1.15748318, -1.27033736, -1.32785245, -2.        ],
       [ 0.04681295, -0.53534059, -0.31887713, -0.42928778, -2.        ],
       [-0.59403076, -0.22432599,  1.14596339,  1.00624313, -2.        ]])

In [9]:
# Method 3
np.append(a,np.full((3,1),-2),axis=1)

array([[ 1.8841606 , -1.15748318, -1.27033736, -1.32785245, -2.        ],
       [ 0.04681295, -0.53534059, -0.31887713, -0.42928778, -2.        ],
       [-0.59403076, -0.22432599,  1.14596339,  1.00624313, -2.        ]])

In [10]:
np.full((3,1),-2)

array([[-2],
       [-2],
       [-2]])