In [1]:
# There is a 4X4 2D Array
# access last 2 rows
# access middle 2 rows
# access 1st and last row
# access 2nd and last row
# access last 3 rows

In [2]:
import numpy as np

In [3]:
a = np.random.randn(4,4)

In [4]:
a

array([[-0.26089987, -0.21310465, -0.37975959, -0.38514005],
       [ 1.13582532,  2.26864913, -0.29117017,  0.54030497],
       [ 0.18042065, -1.04127084,  0.00385593,  1.09281585],
       [-1.11396058, -0.46089338, -0.9666144 , -0.72658954]])

In [5]:
# access last 2 rows
a[2:]

array([[ 0.18042065, -1.04127084,  0.00385593,  1.09281585],
       [-1.11396058, -0.46089338, -0.9666144 , -0.72658954]])

In [6]:
# access middle 2 rows
a[1:3]

array([[ 1.13582532,  2.26864913, -0.29117017,  0.54030497],
       [ 0.18042065, -1.04127084,  0.00385593,  1.09281585]])

In [7]:
# access 1st and last row
a[0::3]

array([[-0.26089987, -0.21310465, -0.37975959, -0.38514005],
       [-1.11396058, -0.46089338, -0.9666144 , -0.72658954]])

In [8]:
# access 2nd and last row
a[1::2]

array([[ 1.13582532,  2.26864913, -0.29117017,  0.54030497],
       [-1.11396058, -0.46089338, -0.9666144 , -0.72658954]])

In [9]:
# access last 3 rows
a[1:]

array([[ 1.13582532,  2.26864913, -0.29117017,  0.54030497],
       [ 0.18042065, -1.04127084,  0.00385593,  1.09281585],
       [-1.11396058, -0.46089338, -0.9666144 , -0.72658954]])

In [10]:
# access corner elements
# access diagonal elements
# access middle 2 columns and all rows
# access last 2 rows and its first 2 values from each row

In [11]:
a

array([[-0.26089987, -0.21310465, -0.37975959, -0.38514005],
       [ 1.13582532,  2.26864913, -0.29117017,  0.54030497],
       [ 0.18042065, -1.04127084,  0.00385593,  1.09281585],
       [-1.11396058, -0.46089338, -0.9666144 , -0.72658954]])

In [12]:
# access corner elements
a[0::3,0::3]

array([[-0.26089987, -0.38514005],
       [-1.11396058, -0.72658954]])

In [13]:
# access diagonal elements
for i in range(4):
    print(a[i,i])

-0.2608998669159571
2.2686491340696375
0.0038559330826012502
-0.726589538892293


In [14]:
# access middle 2 columns and all rows
a[:,1:3]

array([[-0.21310465, -0.37975959],
       [ 2.26864913, -0.29117017],
       [-1.04127084,  0.00385593],
       [-0.46089338, -0.9666144 ]])

In [15]:
# access last 2 rows and its first 2 values from each row
a[2:,:2]

array([[ 0.18042065, -1.04127084],
       [-1.11396058, -0.46089338]])